server:
  port: 8080
  host: "0.0.0.0"

ollama:
  base_url: "http://localhost:11434"
  model: "qwen:8b"
  timeout: 30s

tools:
  weather:
    enabled: true
    mock_data: true
  calculator:
    enabled: true

logging:
  level: "info"
  format: "json"