basePath: /
definitions:
  handlers.ChatRequest:
    properties:
      message:
        example: 北京今天天气怎么样？
        type: string
    required:
    - message
    type: object
  handlers.ChatResponse:
    properties:
      finished:
        example: true
        type: boolean
      message:
        example: 北京今天天气晴朗，温度15.3°C
        type: string
      tool_calls:
        items:
          $ref: '#/definitions/handlers.ToolCallResponse'
        type: array
    type: object
  handlers.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: Invalid request
        type: string
      message:
        example: 请求参数错误
        type: string
    type: object
  handlers.FunctionCallResponse:
    properties:
      arguments: {}
      name:
        example: get_weather
        type: string
    type: object
  handlers.ToolCallResponse:
    properties:
      function:
        $ref: '#/definitions/handlers.FunctionCallResponse'
      id:
        example: call_1
        type: string
      result: {}
      type:
        example: function
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 智能路由调度系统API文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AI Scheduler API
  version: "1.0"
paths:
  /api/v1/chat:
    post:
      consumes:
      - application/json
      description: 发送消息给AI助手，支持工具调用
      parameters:
      - description: 聊天请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 聊天响应
          schema:
            $ref: '#/definitions/handlers.ChatResponse'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: 智能聊天
      tags:
      - chat
  /health:
    get:
      description: 检查服务是否正常运行
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 健康检查
      tags:
      - system
swagger: "2.0"
